---
- name: Set hostname Workers
  hostname:
    name: "{{ ansible_hostname }}"
  with_ansible_hostname:
    - worker1
    - worker2

- name: Copy join to nodes
  copy:
    dest: /opt/kubejoin.sh
    src: ./join/kubejoin.sh
    mode: '0700'

- name: Run command on remote
  shell: /opt/kubejoin.sh
...