---
- name: Set hostname Workers
  command: uname -n
  register: uname_worker
  shell: hostnamectl set-hostname worker-{{ uname_worker }}

- name: Copy join to nodes
  copy:
    dest: /opt/kubejoin.sh
    src: ./join/kubejoin.sh
    mode: '0700'

- name: Run command on remote
  shell: /opt/kubejoin.sh
...